BaseUrl: http://shalomgemeinde.handmadegame.dev

# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Shalom Gemeinde"
description: >- # 	"Template for the Shalome Gemeinde page"
author:              "Márcio Freitas"
title: Shalom Gemeinde
email: marciovmf@gmail.com
://example.com
twitter_username: marciovmf
github_username:  marciovmf

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
