# Development Url
baseUrl: http://localhost:4000

# Production Url
#baseUrl: https://gamedevbr-podcast.github.io

# Social Media
linkGithub: https://github.com/marciovmf/shalomgemeinde

# Site Settings

title: Shalom Gemeinde
email: marciovmf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "http://shalomgemeinde.github.io" # the subpath of your site, e.g. /blog
url: "http://shalomgemeinde.github.io" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marciovmf
github_username:  marciovmf

paginate: 20
permalink: /:title/
post_dirs: false

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
